server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: public-service-api
          uri: http://localhost:443
          predicates:
            - Path=/service-api/open-api/**
          filters:
            - RewritePath="/service-api/(?<segment>/?.*)", "$\{segment}"
            - ServiceApiFilter
